// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb1rO3gSoywaTMn4fsAMuzefbpRf67IN8',
    appId: '1:892300737050:web:ade4696193843bcfa1efa3',
    messagingSenderId: '892300737050',
    projectId: 'laptrinhmobile-15bd9',
    authDomain: 'laptrinhmobile-15bd9.firebaseapp.com',
    storageBucket: 'laptrinhmobile-15bd9.firebasestorage.app',
    measurementId: 'G-GBFLHE6F02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs9tZXAks9p1ViSNnhHWhwNr4ygK54-fU',
    appId: '1:892300737050:android:b1c546acc4cb4036a1efa3',
    messagingSenderId: '892300737050',
    projectId: 'laptrinhmobile-15bd9',
    storageBucket: 'laptrinhmobile-15bd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUHZcTj6m6M5-BRcnkRoyOyN1g9GSitgs',
    appId: '1:892300737050:ios:c9aa4acb57ed6173a1efa3',
    messagingSenderId: '892300737050',
    projectId: 'laptrinhmobile-15bd9',
    storageBucket: 'laptrinhmobile-15bd9.firebasestorage.app',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUHZcTj6m6M5-BRcnkRoyOyN1g9GSitgs',
    appId: '1:892300737050:ios:c9aa4acb57ed6173a1efa3',
    messagingSenderId: '892300737050',
    projectId: 'laptrinhmobile-15bd9',
    storageBucket: 'laptrinhmobile-15bd9.firebasestorage.app',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb1rO3gSoywaTMn4fsAMuzefbpRf67IN8',
    appId: '1:892300737050:web:420f0e54af6177b8a1efa3',
    messagingSenderId: '892300737050',
    projectId: 'laptrinhmobile-15bd9',
    authDomain: 'laptrinhmobile-15bd9.firebaseapp.com',
    storageBucket: 'laptrinhmobile-15bd9.firebasestorage.app',
    measurementId: 'G-FV13WS2NF0',
  );

}